### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by Bumbadawg**

### CODE REVIEW

**Comment by Bumbadawg** [comment]
https://github.com/Bumbadawg/DNF_Tower/blob/4cf1a317c098e5cbf22bab4e4c5ed988283a5147/README.md

**Comment by ayomeer** [comment]
Is this something you worked out with the initiators of the idea or how you interpreted it? Sounds quite different to what was pitched to me. It sounds like you intended the masters to be dynamic, so the one who beat the master becomes the new one, which is a cool motivator to make people "get back their rank". I guess we should define the actual idea better first if we have these sorts of questions. Can you have multiple '.md' files? I'd be happy to merge it as not the defacto ReadMe of the project.

**Comment by aesick** [comment]
I like the ideas, lets get over them via voice chat. If i guess correctly thats the process of challenging a floor master for the master spot.

**Comment by Bumbadawg** [comment]
` It sounds like you intended the masters to be dynamic, so the one who beat the master becomes the new one` yes indeed 

like n0cturn3 said 
`I think it works out, a floormaster of floor 4 could be rank 6 because they can take maps off the next 2 floor masters but haven't won a bo5 against them. And the same way, someone might take their map to reach rank 4 or 5, but they aren't a floor master because they might lose in a bo5.
,`

but i won't be available for few days to discuss it by chat, i'll get a smartphone connection on github/discord to text it though :)

**Comment by aesick** [comment]
I think you mix the 2 aspects here. The Idea is to have a Ranking System for the Tower rank0 - 10. Rank0 are unranked Players, who havent played a game yet. On each floor from 1-10 resides 1 or more floor masters. Players/challengers can challenge a floor master and rise in rank if they beat him -> rank0 Player beats floor master of floor1 in bo1 = advance from rank0 to rank1. The floor master stays on the floor 1. If the challenger is interessted he can try to become floor master of floor1 by beating the current master in a bo5 format. If he wins, he is now the floor master of floor1. The question is now, if the beaten floor master drops down or stays a floor master.
I hope my example was understandable.

**Comment by ayomeer** [comment]
Yeah I understand, thx :)

**Comment by Bumbadawg** [comment]
@aesick Understood :)

So as for the definitions gentlemen @orouvinen @ayomeer @aesick, 
let's try to get it concise and clear once and for all :

- **Tower** ?
Since each player masters differently each map, I propose one tower per map.
One could rox Aero and get owned hard on ZTN. 
A tower has got multiple floors.
Each floor has got **ONE** master minimum/maximum.

- **Ranking** ?
A player can be of any rank [0-10] for instance in a given Tower.
A rank is tracked by the best floor master beaten of the given Tower.

- **Floor** ?
A floor is defined by its master. No master == no floor appreciation.
One master leaving a floor **MUST** be replaced by another. Otherwise there is no track of _what defines a floor_.

- **Master** ?
I propose this:
To challenge the master ;
One player must be ranked as high as the floor master (and not more).
He must have been defeated by higher masters at least 10 times.
So if **_Evil_** can beat any higher masters, he cannot be able to challenge the current floor master.
The master **MUST** accept if available. 
May it be bo1 (if the master don't want to be master anymore, or bo7 if he wants a grueling challenge.
The winner defines the floor: if previous master if vanquished, he goes back to the pool of players. _That also means new master is better than before_. So we have to consider floors/ranks will be harder and harder to be gained over time folks :-)
But WHAT IF one master leaves Quake for ever :-( ?
Well to counter this eventuality we could have multiple masters at once for one floor. So we avoid getting short of masters.

Again let's be concise, write down what your toughts are. Let's mix our ideas :-)

**Comment by ayomeer** [comment]
aesick already defined a lot of aspects in Tower of Death_Rules.doc but we can can have the discussion here. @aesick if you want to give changes you make to the repository more visibility and give people a chance to discuss them like here, open a pull request, when you upload files or make big changes. :)

It's hard to have discussions about *the whole system* in this one thread. I'll create a bunch if issues to split it up into the aspects that we think need to be refined. Also so we don't just have a pile of ideas: I'll take our lead game designer aesick's initial ideas as "master" and have you argue why we should do it differently :p 

EDIT: Actually I'm just gonna let you create Issues yourself. I made a project "Whiteboard" where you  can add issues into the various categories. When you propose changes, keep in mind the purpose of the system. It should encourage tutoring and focused learning on each map. The competition aspect is merely some added fun. Also don't get lost in the details just yet ;)

**Pull request merged**
